Add support for .sbat version information

diff --git a/mkdistrib b/mkdistrib
--- a/mkdistrib
+++ b/mkdistrib
@@ -1,12 +1,15 @@
 #!/usr/bin/env bash
 #
 # Script to prepare source code and binary distribution files of rEFInd.
-# By Rod Smith, 3/11/2012
+# Copyright Rod Smith, 2012-2023
+# Licensed under the terms of the GNU GPL-3
+#
 # Updated 11/8/2012 to do more things automatically
 # Updated 12/6/2012 to sign binaries with the rEFInd MOK
 # Updated 12/3/2015 to independently compile .zip, RPM, and Debian packages
+# Updated 2/20/2023 to support creating .sbat section
 #
-# Usage: ./mkdistrib [--nosign] [--norpm] [--nodebian] [--nozip] version
+# Usage: ./mkdistrib [--nosign [--nosbat]] [--norpm] [--nodebian] [--nozip] version
 # where "version" is a version number.
 #
 # Build requirements:
@@ -22,6 +25,7 @@
 #    not signed. Only X64 binaries are signed.
 
 SignIt=1
+Sbat=1
 MakeRpm=1
 MakeDebian=1
 MakeZip=1
@@ -29,10 +33,11 @@ KeysDir=/mnt/refind
 KeysInfo=$(df $KeysDir 2> /dev/null | grep $KeysDir)
 StartDir=$(pwd)
 SBSign=$(command -v sbsign 2> /dev/null)
+ObjCopy=$(command -v objcopy 2> /dev/null)
 
 ShowUsage() {
    echo "Usage:"
-   echo "$0 [--nosign] [--norpm] [--nodebian] [--nozip] version"
+   echo "$0 [--nosign ] [--nosbat] [--norpm] [--nodebian] [--nozip] version"
    exit
 }
 
@@ -41,6 +46,8 @@ GetParams() {
       echo "$1"
       case "$1" in
          --nosign) SignIt=0
+              ;;
+         --nosbat) Sbat=0
               ;;
          --norpm) MakeRpm=0
               ;;
@@ -72,7 +79,8 @@ MakeTarball() {
     cp -a debian docs images keys fonts banners include EfiLib libeg gzip mok net refind filesystems \
         gptsync refind.spec refind-install refind-mkdefault mkrlconf mvrefind mountesp CREDITS.txt \
         NEWS.txt BUILDING.txt COPYING.txt LICENSE.txt README.txt refind.inf gptsync.inf \
-        Make.common Makefile refind.conf-sample RefindPkg.d?? "$TargetDir"/refind-"$Version"
+        Make.common Makefile refind.conf-sample RefindPkg.d?? refind-sbat.csv refind-sbat-local.csv \
+        "$TargetDir"/refind-"$Version"
 
     # Go there and prepare a souce code tarball....
     cd "$TargetDir"
@@ -96,6 +104,7 @@ MakeZipBinary() {
     ARCH=aarch64 make -j1
     ARCH=aarch64 make fs
     mkdir -p refind-bin-"$Version"/refind/drivers_aa64
+    cp -a refind-sbat.csv refind-sbat-local.csv refind-bin-"$Version"/
     cp --preserve=timestamps drivers_aa64/*_aa64.efi refind-bin-"$Version"/refind/drivers_aa64/
     cp --preserve=timestamps filesystems/LICENSE*txt refind-bin-"$Version"/refind/drivers_aa64/
     cp refind/refind_aa64.efi refind-bin-"$Version"/refind/refind_aa64.efi
@@ -109,6 +118,7 @@ MakeZipBinary() {
     ARCH=ia32 make -j1
     ARCH=ia32 make fs
     mkdir -p refind-bin-"$Version"/refind/drivers_ia32
+    cp -a refind-sbat.csv refind-sbat-local.csv refind-bin-"$Version"/
     cp --preserve=timestamps drivers_ia32/*_ia32.efi refind-bin-"$Version"/refind/drivers_ia32/
     cp --preserve=timestamps filesystems/LICENSE*txt refind-bin-"$Version"/refind/drivers_ia32/
     cp refind/refind_ia32.efi refind-bin-"$Version"/refind/refind_ia32.efi
@@ -121,11 +131,17 @@ MakeZipBinary() {
     make -j1
     make fs
     mkdir -p refind-bin-"$Version"/refind/drivers_x64
+    cp -a refind-sbat.csv refind-sbat-local.csv refind-bin-"$Version"/
     cp -a icons refind-bin-"$Version"/refind/
     if [[ $SignIt == 1 ]] ; then
         for File in drivers_x64/*_x64.efi ; do
-            $SBSign --key "$KeysDir"/refind.key --cert "$KeysDir"/refind.crt \
-                    --output refind-bin-"$Version"/refind/"$File" "$File"
+            if [[ $Sbat == 1 ]] ; then
+                "$ObjCopy" --set-section-alignment '.sbat=512' --add-section \
+                           .sbat=refind-bin-"$Version"/refind-sbat.csv \
+                           --adjust-section-vma .sbat+10000000 "$File"
+            fi
+            "$SBSign" --key "$KeysDir"/refind.key --cert "$KeysDir"/refind.crt \
+                      --output refind-bin-"$Version"/refind/"$File" "$File"
         done
     else
         cp --preserve=timestamps drivers_x64/*_x64.efi refind-bin-"$Version"/refind/drivers_x64/
@@ -133,15 +149,25 @@ MakeZipBinary() {
     cp --preserve=timestamps filesystems/LICENSE*txt refind-bin-"$Version"/refind/drivers_x64/
     cp --preserve=timestamps refind.conf-sample refind-bin-"$Version"/refind/
     if [[ $SignIt == 1 ]] ; then
-        "$SBSign" --key "$KeysDir"/refind.key --cert "$KeysDir"/refind.crt \
+            if [[ $Sbat == 1 ]] ; then
+                "$ObjCopy" --set-section-alignment '.sbat=512' --add-section \
+                           .sbat=refind-bin-"$Version"/refind-sbat.csv \
+                           --adjust-section-vma .sbat+10000000 refind/refind_x64.efi
+            fi
+            "$SBSign" --key "$KeysDir"/refind.key --cert "$KeysDir"/refind.crt \
                   --output refind-bin-"$Version"/refind/refind_x64.efi refind/refind_x64.efi
     else
         cp refind/refind_x64.efi refind-bin-"$Version"/refind/refind_x64.efi
     fi
     mkdir -p refind-bin-"$Version"/refind/tools_x64
     if [[ $SignIt == 1 ]] ; then
-        $SBSign --key "$KeysDir"/refind.key --cert "$KeysDir"/refind.crt \
-                --output refind-bin-"$Version"/refind/tools_x64/gptsync_x64.efi gptsync/gptsync_x64.efi
+            if [[ $Sbat == 1 ]] ; then
+                "$ObjCopy" --set-section-alignment '.sbat=512' --add-section \
+                           .sbat=refind-bin-"$Version"/refind-sbat.csv \
+                           --adjust-section-vma .sbat+10000000 gptsync/gptsync_x64.efi
+            fi
+        "$SBSign" --key "$KeysDir"/refind.key --cert "$KeysDir"/refind.crt \
+                  --output refind-bin-"$Version"/refind/tools_x64/gptsync_x64.efi gptsync/gptsync_x64.efi
     else
         cp --preserve=timestamps gptsync/gptsync_x64.efi refind-bin-"$Version"/refind/tools_x64/
     fi
@@ -156,8 +182,13 @@ MakeZipBinary() {
     make clean
     make -j1 gnuefi
     if [[ $SignIt == 1 ]] ; then
-        $SBSign --key "$KeysDir"/refind.key --cert "$KeysDir"/refind.crt \
-                --output refind-bin-"$Version"/refind/refind_x64.efi refind/refind_x64.efi
+        if [[ $Sbat == 1 ]] ; then
+            "$ObjCopy" --set-section-alignment '.sbat=512' --add-section \
+                       .sbat=refind-bin-"$Version"/refind-sbat.csv \
+                       --adjust-section-vma .sbat+10000000 refind/refind_x64.efi
+        fi
+        "$SBSign" --key "$KeysDir"/refind.key --cert "$KeysDir"/refind.crt \
+                  --output refind-bin-"$Version"/refind/refind_x64.efi refind/refind_x64.efi
     else
         cp refind/refind_x64.efi refind-bin-"$Version"/refind/refind_x64.efi
     fi
@@ -238,6 +269,11 @@ echo "$TargetDir"
 if [[ -z $SBSign && $SignIt == 1 ]] ; then
    echo "Can't find sbsign binary! Aborting!"
    exit 1
+fi
+
+if [[ -z "$ObjCopy" && "$Sbat" == 1 ]] ; then
+    echo "Can't find objcopy (needed for .sbat)! Aborting!"
+    exit 1
 fi
 
 if [[ -z $KeysInfo && $SignIt == 1 ]] ; then
